trigger:
  - azdo/dev*

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '8'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
  - task: MavenAuthenticate@0
    inputs:
      artifactsFeeds: 'eutils.feed'
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean deploy'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false